### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by lmiller1990** [stewart/weather-api#7]
Hi,

I am using this for a small personal project, great gem. I wanted to add support for returning queries in languages other than English, but later realised Yahoo didn't support this feature. None the less, forked and pulled the repo and noticed a few tests failing - perhaps the json that is returned changed slightly?

Fixed the tests to be all green. API still works fine either way, but if you are interested I can make a PR with my fixes.

If there is anything else you'd like to see added or changed lmk, I'm happy to contribute.

**Comment by stewart** [comment]
Hi @lmiller1990 - thanks for letting me know! I've corrected the behaviours causing test failures, and pushed a new release with the fixups (`v.1.3.0`).
