### ISSUE TITLE
Failed to get weather

### ISSUE THREAD

**Issue by gzmarques** [stewart/weather-api#8]
Hi all,

I don't know if i'm missing something... I just added the lookup method in my controller and it keep failing to get the response:

> Failed to get weather [url=http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%3D455866%20and%20u%3D'c'&format=json, e=execution expired].

Yet the link is completely accessible from browser directly.

Thanks

**Comment by stewart** [comment]
Hi, can you check whether or not this test script works for you?

```ruby
require 'weather-api'

response = Weather.lookup(455866, Weather::Units::CELSIUS)

print <<EOT
#{response.title}
#{response.condition.temp} degrees
#{response.condition.text}
EOT
```

For me, this works correctly:

    $ ruby test.rb
    Conditions for Guarapuava, PR, BR at 11:00 PM BRT
    19 degrees
    Clear

**Comment by gzmarques** [comment]
Sorry, it's working now... Don't know why it was missing the GET response, returning me timeout error

But now it's ok, thanks :)
